language: generic
sudo : required
services: 
  - docker:
     
before_install:
  - docker build -t devathrao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devathrao/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-324739892705"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $Aws_Access_key
  secret_access_key: $Secret_access_key
